/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#define ORBIT_IDL_C_COMMON
#define GNOME_VFS_Daemon_COMMON
#include "GNOME_VFS_Daemon.h"

static const CORBA_unsigned_long ORBit_zero_int = 0;

#if ( (TC_IMPL_TC_GNOME_VFS_Client_0 == 'G') \
&& (TC_IMPL_TC_GNOME_VFS_Client_1 == 'N') \
&& (TC_IMPL_TC_GNOME_VFS_Client_2 == 'O') \
&& (TC_IMPL_TC_GNOME_VFS_Client_3 == 'M') \
&& (TC_IMPL_TC_GNOME_VFS_Client_4 == 'E') \
&& (TC_IMPL_TC_GNOME_VFS_Client_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Client_6 == 'V') \
&& (TC_IMPL_TC_GNOME_VFS_Client_7 == 'F') \
&& (TC_IMPL_TC_GNOME_VFS_Client_8 == 'S') \
&& (TC_IMPL_TC_GNOME_VFS_Client_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Client_10 == 'D') \
&& (TC_IMPL_TC_GNOME_VFS_Client_11 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Client_12 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Client_13 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Client_14 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Client_15 == 'n') \
) && !defined(TC_DEF_TC_GNOME_VFS_Client)
#define TC_DEF_TC_GNOME_VFS_Client 1
#ifdef ORBIT_IDL_C_IMODULE_GNOME_VFS_Daemon
static
#endif
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Client_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_objref,
   0,
   0,
   4,
   0,
   0,
   NULL,
   CORBA_OBJECT_NIL,
   "Client",
   "IDL:GNOME/VFS/Client:1.0",
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_VFS_Daemon_0 == 'G') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_1 == 'N') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_2 == 'O') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_3 == 'M') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_4 == 'E') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_5 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_6 == 'V') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_7 == 'F') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_8 == 'S') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_9 == '_') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_10 == 'D') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_11 == 'a') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_12 == 'e') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_13 == 'm') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_14 == 'o') \
&& (TC_IMPL_TC_GNOME_VFS_Daemon_15 == 'n') \
) && !defined(TC_DEF_TC_GNOME_VFS_Daemon)
#define TC_DEF_TC_GNOME_VFS_Daemon 1
#ifdef ORBIT_IDL_C_IMODULE_GNOME_VFS_Daemon
static
#endif
const struct CORBA_TypeCode_struct TC_GNOME_VFS_Daemon_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_objref,
   0,
   0,
   4,
   0,
   0,
   NULL,
   CORBA_OBJECT_NIL,
   "Daemon",
   "IDL:GNOME/VFS/Daemon:1.0",
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif

#ifndef ORBIT_IDL_C_IMODULE_GNOME_VFS_Daemon
CORBA_unsigned_long GNOME_VFS_Client__classid = 0;
#endif

#ifndef ORBIT_IDL_C_IMODULE_GNOME_VFS_Daemon
CORBA_unsigned_long GNOME_VFS_Daemon__classid = 0;
#endif

/* Interface type data */

static ORBit_IArg GNOME_VFS_Client_doSomething__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "aStr"}
};

#ifdef ORBIT_IDL_C_IMODULE_GNOME_VFS_Daemon
static
#endif
ORBit_IMethod GNOME_VFS_Client__imethods[] = {
   {
    {1, 1, GNOME_VFS_Client_doSomething__arginfo, FALSE},
    {0, 0, NULL, FALSE},
    {0, 0, NULL, FALSE},
    TC_void, "doSomething", 11,
    0}
};
static CORBA_string GNOME_VFS_Client__base_itypes[] = {
   "IDL:Bonobo/Unknown:1.0",
   "IDL:omg.org/CORBA/Object:1.0"
};

#ifdef ORBIT_IDL_C_IMODULE_GNOME_VFS_Daemon
static
#endif
ORBit_IInterface GNOME_VFS_Client__iinterface = {
   TC_GNOME_VFS_Client, {1, 1, GNOME_VFS_Client__imethods, FALSE},
   {2, 2, GNOME_VFS_Client__base_itypes, FALSE}
};

static ORBit_IArg GNOME_VFS_Daemon_setPassword__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "uri"},
   {TC_CORBA_string, ORBit_I_ARG_IN, "user"},
   {TC_CORBA_string, ORBit_I_ARG_IN, "passwd"}
};
static ORBit_IArg GNOME_VFS_Daemon_getPassword__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "uri"},
   {TC_CORBA_string, ORBit_I_ARG_IN, "user"}
};
static ORBit_IArg GNOME_VFS_Daemon_registerClient__arginfo[] = {
   {TC_GNOME_VFS_Client, ORBit_I_ARG_IN, "client"}
};
static ORBit_IArg GNOME_VFS_Daemon_deRegisterClient__arginfo[] = {
   {TC_GNOME_VFS_Client, ORBit_I_ARG_IN, "client"}
};

#ifdef ORBIT_IDL_C_IMODULE_GNOME_VFS_Daemon
static
#endif
ORBit_IMethod GNOME_VFS_Daemon__imethods[] = {
   {
    {3, 3, GNOME_VFS_Daemon_setPassword__arginfo, FALSE},
    {0, 0, NULL, FALSE},
    {0, 0, NULL, FALSE},
    TC_void, "setPassword", 11,
    0}
   , {
      {2, 2, GNOME_VFS_Daemon_getPassword__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_CORBA_string, "getPassword", 11,
      0}
   , {
      {1, 1, GNOME_VFS_Daemon_registerClient__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_void, "registerClient", 14,
      0}
   , {
      {1, 1, GNOME_VFS_Daemon_deRegisterClient__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_void, "deRegisterClient", 16,
      0}
};
static CORBA_string GNOME_VFS_Daemon__base_itypes[] = {
   "IDL:Bonobo/Unknown:1.0",
   "IDL:omg.org/CORBA/Object:1.0"
};

#ifdef ORBIT_IDL_C_IMODULE_GNOME_VFS_Daemon
static
#endif
ORBit_IInterface GNOME_VFS_Daemon__iinterface = {
   TC_GNOME_VFS_Daemon, {4, 4, GNOME_VFS_Daemon__imethods, FALSE},
   {2, 2, GNOME_VFS_Daemon__base_itypes, FALSE}
};
