/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "GNOME_VFS_Daemon.h"

void
GNOME_VFS_Client_doSomething(GNOME_VFS_Client _obj, const CORBA_char * aStr,
			     CORBA_Environment * ev)
{
   POA_GNOME_VFS_Client__epv *_ORBIT_epv;

   if (ORBit_small_flags & ORBIT_SMALL_FAST_LOCALS &&
       ORBIT_STUB_IsBypass(_obj, GNOME_VFS_Client__classid) &&
       (_ORBIT_epv =
	ORBIT_STUB_GetEpv(_obj, GNOME_VFS_Client__classid))->doSomething) {
      ORBIT_STUB_PreCall(_obj);
      _ORBIT_epv->doSomething(ORBIT_STUB_GetServant(_obj), aStr, ev);
      ORBIT_STUB_PostCall(_obj);
   } else {			/* remote marshal */
      gpointer _args[] = {
	 (gpointer) & aStr
      };

      ORBit_small_invoke_stub_n(_obj, &GNOME_VFS_Client__iinterface.methods,
				0, NULL, _args, NULL, ev);

   }
}
void
GNOME_VFS_Daemon_setPassword(GNOME_VFS_Daemon _obj, const CORBA_char * key,
			     const CORBA_char * passwd,
			     CORBA_Environment * ev)
{
   POA_GNOME_VFS_Daemon__epv *_ORBIT_epv;

   if (ORBit_small_flags & ORBIT_SMALL_FAST_LOCALS &&
       ORBIT_STUB_IsBypass(_obj, GNOME_VFS_Daemon__classid) &&
       (_ORBIT_epv =
	ORBIT_STUB_GetEpv(_obj, GNOME_VFS_Daemon__classid))->setPassword) {
      ORBIT_STUB_PreCall(_obj);
      _ORBIT_epv->setPassword(ORBIT_STUB_GetServant(_obj), key, passwd, ev);
      ORBIT_STUB_PostCall(_obj);
   } else {			/* remote marshal */
      gpointer _args[] = {
	 (gpointer) & key, (gpointer) & passwd
      };

      ORBit_small_invoke_stub_n(_obj, &GNOME_VFS_Daemon__iinterface.methods,
				0, NULL, _args, NULL, ev);

   }
}
CORBA_string
GNOME_VFS_Daemon_getPassword(GNOME_VFS_Daemon _obj, const CORBA_char * key,
			     CORBA_Environment * ev)
{
   CORBA_string _ORBIT_retval;
   POA_GNOME_VFS_Daemon__epv *_ORBIT_epv;

   if (ORBit_small_flags & ORBIT_SMALL_FAST_LOCALS &&
       ORBIT_STUB_IsBypass(_obj, GNOME_VFS_Daemon__classid) &&
       (_ORBIT_epv =
	ORBIT_STUB_GetEpv(_obj, GNOME_VFS_Daemon__classid))->getPassword) {
      ORBIT_STUB_PreCall(_obj);
      _ORBIT_retval =
	 _ORBIT_epv->getPassword(ORBIT_STUB_GetServant(_obj), key, ev);
      ORBIT_STUB_PostCall(_obj);
   } else {			/* remote marshal */
      gpointer _args[] = {
	 (gpointer) & key
      };

      ORBit_small_invoke_stub_n(_obj, &GNOME_VFS_Daemon__iinterface.methods,
				1, &_ORBIT_retval, _args, NULL, ev);

   }
   return _ORBIT_retval;
}

void
GNOME_VFS_Daemon_registerClient(GNOME_VFS_Daemon _obj,
				const GNOME_VFS_Client client,
				CORBA_Environment * ev)
{
   POA_GNOME_VFS_Daemon__epv *_ORBIT_epv;

   if (ORBit_small_flags & ORBIT_SMALL_FAST_LOCALS &&
       ORBIT_STUB_IsBypass(_obj, GNOME_VFS_Daemon__classid) &&
       (_ORBIT_epv =
	ORBIT_STUB_GetEpv(_obj, GNOME_VFS_Daemon__classid))->registerClient) {
      ORBIT_STUB_PreCall(_obj);
      _ORBIT_epv->registerClient(ORBIT_STUB_GetServant(_obj), client, ev);
      ORBIT_STUB_PostCall(_obj);
   } else {			/* remote marshal */
      gpointer _args[] = {
	 (gpointer) & client
      };

      ORBit_small_invoke_stub_n(_obj, &GNOME_VFS_Daemon__iinterface.methods,
				2, NULL, _args, NULL, ev);

   }
}
void
GNOME_VFS_Daemon_deRegisterClient(GNOME_VFS_Daemon _obj,
				  const GNOME_VFS_Client client,
				  CORBA_Environment * ev)
{
   POA_GNOME_VFS_Daemon__epv *_ORBIT_epv;

   if (ORBit_small_flags & ORBIT_SMALL_FAST_LOCALS &&
       ORBIT_STUB_IsBypass(_obj, GNOME_VFS_Daemon__classid) &&
       (_ORBIT_epv =
	ORBIT_STUB_GetEpv(_obj,
			  GNOME_VFS_Daemon__classid))->deRegisterClient) {
      ORBIT_STUB_PreCall(_obj);
      _ORBIT_epv->deRegisterClient(ORBIT_STUB_GetServant(_obj), client, ev);
      ORBIT_STUB_PostCall(_obj);
   } else {			/* remote marshal */
      gpointer _args[] = {
	 (gpointer) & client
      };

      ORBit_small_invoke_stub_n(_obj, &GNOME_VFS_Daemon__iinterface.methods,
				3, NULL, _args, NULL, ev);

   }
}
