#include <Bonobo_Unknown.idl>

module GNOME {
	module VFS {
		exception NotFound {};
		struct AuthInfo {
			string username;
			string password;
		};

		typedef sequence<AuthInfo>  AuthInfoList;

		interface Client : Bonobo::Unknown {
			void doSomething (in string aStr);
		};

		interface Daemon : Bonobo::Unknown {
			/* Central Password storage */
			void   setPassword (in string uri, 
					    in string user, 
					    in string passwd);
			AuthInfoList getPassword (in string uri,
						  in string user);

			AuthInfoList getAllPasswords (in string uri);

			/* Lifecycle slaved to 'client' lifecycle */
			void registerClient   (in Client client);
			void deRegisterClient (in Client client);
		};
	};
};
