/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "GNOME_VFS_Daemon.h"

void
_ORBIT_skel_small_GNOME_VFS_Client_doSomething(POA_GNOME_VFS_Client *
					       _o_servant, gpointer _o_retval,
					       gpointer * _o_args,
					       CORBA_Context _o_ctx,
					       CORBA_Environment * _o_ev,
					       void (*_impl_doSomething)
					       (PortableServer_Servant
						_servant,
						const CORBA_char * aStr,
						CORBA_Environment * ev))
{
   _impl_doSomething(_o_servant, *(const CORBA_char * *) _o_args[0], _o_ev);
}

void
_ORBIT_skel_small_GNOME_VFS_Daemon_setPassword(POA_GNOME_VFS_Daemon *
					       _o_servant, gpointer _o_retval,
					       gpointer * _o_args,
					       CORBA_Context _o_ctx,
					       CORBA_Environment * _o_ev,
					       void (*_impl_setPassword)
					       (PortableServer_Servant
						_servant,
						const CORBA_char * key,
						const CORBA_char * passwd,
						CORBA_Environment * ev))
{
   _impl_setPassword(_o_servant, *(const CORBA_char * *) _o_args[0],
		     *(const CORBA_char * *) _o_args[1], _o_ev);
}

void
_ORBIT_skel_small_GNOME_VFS_Daemon_getPassword(POA_GNOME_VFS_Daemon *
					       _o_servant, gpointer _o_retval,
					       gpointer * _o_args,
					       CORBA_Context _o_ctx,
					       CORBA_Environment * _o_ev,
					       CORBA_string
					       (*_impl_getPassword)
					       (PortableServer_Servant
						_servant,
						const CORBA_char * key,
						CORBA_Environment * ev))
{
   *(CORBA_string *) _o_retval =
      _impl_getPassword(_o_servant, *(const CORBA_char * *) _o_args[0],
			_o_ev);
}

void
_ORBIT_skel_small_GNOME_VFS_Daemon_registerClient(POA_GNOME_VFS_Daemon *
						  _o_servant,
						  gpointer _o_retval,
						  gpointer * _o_args,
						  CORBA_Context _o_ctx,
						  CORBA_Environment * _o_ev,
						  void (*_impl_registerClient)
						  (PortableServer_Servant
						   _servant,
						   const GNOME_VFS_Client
						   client,
						   CORBA_Environment * ev))
{
   _impl_registerClient(_o_servant, *(const GNOME_VFS_Client *) _o_args[0],
			_o_ev);
}

void
_ORBIT_skel_small_GNOME_VFS_Daemon_deRegisterClient(POA_GNOME_VFS_Daemon *
						    _o_servant,
						    gpointer _o_retval,
						    gpointer * _o_args,
						    CORBA_Context _o_ctx,
						    CORBA_Environment * _o_ev,
						    void
						    (*_impl_deRegisterClient)
						    (PortableServer_Servant
						     _servant,
						     const GNOME_VFS_Client
						     client,
						     CORBA_Environment * ev))
{
   _impl_deRegisterClient(_o_servant, *(const GNOME_VFS_Client *) _o_args[0],
			  _o_ev);
}
static ORBitSmallSkeleton
get_skel_small_GNOME_VFS_Client(POA_GNOME_VFS_Client * servant,
				const char *opname, gpointer * m_data,
				gpointer * impl)
{
   switch (opname[0]) {
     case 'd':
	if (strcmp((opname + 1), "oSomething"))
	   break;
	*impl = (gpointer) servant->vepv->GNOME_VFS_Client_epv->doSomething;
	*m_data =
	   (gpointer) & GNOME_VFS_Client__iinterface.methods._buffer[0];
	return (ORBitSmallSkeleton)
	   _ORBIT_skel_small_GNOME_VFS_Client_doSomething;
	break;
     case 'q':
	if (strcmp((opname + 1), "ueryInterface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->queryInterface;
	*m_data = (gpointer) & Bonobo_Unknown__iinterface.methods._buffer[2];
	return (ORBitSmallSkeleton)
	   _ORBIT_skel_small_Bonobo_Unknown_queryInterface;
	break;
     case 'r':
	if (strcmp((opname + 1), "ef"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
	*m_data = (gpointer) & Bonobo_Unknown__iinterface.methods._buffer[0];
	return (ORBitSmallSkeleton) _ORBIT_skel_small_Bonobo_Unknown_ref;
	break;
     case 'u':
	if (strcmp((opname + 1), "nref"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
	*m_data = (gpointer) & Bonobo_Unknown__iinterface.methods._buffer[1];
	return (ORBitSmallSkeleton) _ORBIT_skel_small_Bonobo_Unknown_unref;
	break;
     default:
	break;
   }
   return NULL;
}

void
POA_GNOME_VFS_Client__init(PortableServer_Servant servant,
			   CORBA_Environment * env)
{
   static PortableServer_ClassInfo class_info =
      { NULL, (ORBit_small_impl_finder) & get_skel_small_GNOME_VFS_Client,
"IDL:GNOME/VFS/Client:1.0", &GNOME_VFS_Client__classid, NULL, &GNOME_VFS_Client__iinterface };
   POA_GNOME_VFS_Client__vepv *fakevepv = NULL;

   if (((PortableServer_ServantBase *) servant)->vepv[0]->finalize == 0) {
      ((PortableServer_ServantBase *) servant)->vepv[0]->finalize =
	 POA_GNOME_VFS_Client__fini;
   }
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBit_classinfo_register(&class_info);
   ORBIT_SERVANT_SET_CLASSINFO(servant, &class_info);

   if (!class_info.vepvmap) {
      class_info.vepvmap =
	 g_new0(ORBit_VepvIdx, GNOME_VFS_Client__classid + 1);
      class_info.vepvmap[Bonobo_Unknown__classid] =
	 (((char *) &(fakevepv->Bonobo_Unknown_epv)) -
	  ((char *) (fakevepv))) / sizeof(GFunc);
      class_info.vepvmap[GNOME_VFS_Client__classid] =
	 (((char *) &(fakevepv->GNOME_VFS_Client_epv)) -
	  ((char *) (fakevepv))) / sizeof(GFunc);
   }
}

void
POA_GNOME_VFS_Client__fini(PortableServer_Servant servant,
			   CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}

static ORBitSmallSkeleton
get_skel_small_GNOME_VFS_Daemon(POA_GNOME_VFS_Daemon * servant,
				const char *opname, gpointer * m_data,
				gpointer * impl)
{
   switch (opname[0]) {
     case 'd':
	if (strcmp((opname + 1), "eRegisterClient"))
	   break;
	*impl =
	   (gpointer) servant->vepv->GNOME_VFS_Daemon_epv->deRegisterClient;
	*m_data =
	   (gpointer) & GNOME_VFS_Daemon__iinterface.methods._buffer[3];
	return (ORBitSmallSkeleton)
	   _ORBIT_skel_small_GNOME_VFS_Daemon_deRegisterClient;
	break;
     case 'g':
	if (strcmp((opname + 1), "etPassword"))
	   break;
	*impl = (gpointer) servant->vepv->GNOME_VFS_Daemon_epv->getPassword;
	*m_data =
	   (gpointer) & GNOME_VFS_Daemon__iinterface.methods._buffer[1];
	return (ORBitSmallSkeleton)
	   _ORBIT_skel_small_GNOME_VFS_Daemon_getPassword;
	break;
     case 'q':
	if (strcmp((opname + 1), "ueryInterface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->queryInterface;
	*m_data = (gpointer) & Bonobo_Unknown__iinterface.methods._buffer[2];
	return (ORBitSmallSkeleton)
	   _ORBIT_skel_small_Bonobo_Unknown_queryInterface;
	break;
     case 'r':
	switch (opname[1]) {
	  case 'e':
	     switch (opname[2]) {
	       case 'f':
		  if (strcmp((opname + 3), ""))
		     break;
		  *impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
		  *m_data =
		     (gpointer) & Bonobo_Unknown__iinterface.methods.
		     _buffer[0];
		  return (ORBitSmallSkeleton)
		     _ORBIT_skel_small_Bonobo_Unknown_ref;
		  break;
	       case 'g':
		  if (strcmp((opname + 3), "isterClient"))
		     break;
		  *impl =
		     (gpointer) servant->vepv->GNOME_VFS_Daemon_epv->
		     registerClient;
		  *m_data =
		     (gpointer) & GNOME_VFS_Daemon__iinterface.methods.
		     _buffer[2];
		  return (ORBitSmallSkeleton)
		     _ORBIT_skel_small_GNOME_VFS_Daemon_registerClient;
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 's':
	if (strcmp((opname + 1), "etPassword"))
	   break;
	*impl = (gpointer) servant->vepv->GNOME_VFS_Daemon_epv->setPassword;
	*m_data =
	   (gpointer) & GNOME_VFS_Daemon__iinterface.methods._buffer[0];
	return (ORBitSmallSkeleton)
	   _ORBIT_skel_small_GNOME_VFS_Daemon_setPassword;
	break;
     case 'u':
	if (strcmp((opname + 1), "nref"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
	*m_data = (gpointer) & Bonobo_Unknown__iinterface.methods._buffer[1];
	return (ORBitSmallSkeleton) _ORBIT_skel_small_Bonobo_Unknown_unref;
	break;
     default:
	break;
   }
   return NULL;
}

void
POA_GNOME_VFS_Daemon__init(PortableServer_Servant servant,
			   CORBA_Environment * env)
{
   static PortableServer_ClassInfo class_info =
      { NULL, (ORBit_small_impl_finder) & get_skel_small_GNOME_VFS_Daemon,
"IDL:GNOME/VFS/Daemon:1.0", &GNOME_VFS_Daemon__classid, NULL, &GNOME_VFS_Daemon__iinterface };
   POA_GNOME_VFS_Daemon__vepv *fakevepv = NULL;

   if (((PortableServer_ServantBase *) servant)->vepv[0]->finalize == 0) {
      ((PortableServer_ServantBase *) servant)->vepv[0]->finalize =
	 POA_GNOME_VFS_Daemon__fini;
   }
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBit_classinfo_register(&class_info);
   ORBIT_SERVANT_SET_CLASSINFO(servant, &class_info);

   if (!class_info.vepvmap) {
      class_info.vepvmap =
	 g_new0(ORBit_VepvIdx, GNOME_VFS_Daemon__classid + 1);
      class_info.vepvmap[Bonobo_Unknown__classid] =
	 (((char *) &(fakevepv->Bonobo_Unknown_epv)) -
	  ((char *) (fakevepv))) / sizeof(GFunc);
      class_info.vepvmap[GNOME_VFS_Daemon__classid] =
	 (((char *) &(fakevepv->GNOME_VFS_Daemon_epv)) -
	  ((char *) (fakevepv))) / sizeof(GFunc);
   }
}

void
POA_GNOME_VFS_Daemon__fini(PortableServer_Servant servant,
			   CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}
