module GNOME {

	module VFS {

		typedef sequence<octet> Buffer;
		typedef unsigned short Result;
		typedef unsigned long OpenMode;
		typedef unsigned short Permission;

		typedef string MetadataKey;
		typedef sequence<string> MetadataKeyList;

		struct Metadata {
			MetadataKey key;
			Buffer value;
		};
		typedef sequence<Metadata> MetadataList;

	};
 
}; 
